components:
  dates:
    start_date: '2022-01-01'
    end_date: '2024-06-01'

  data_preprocessor:
    - sort_values:
        cols:
          - 'ad_id'
          - 'date'
  
    - fillna: 
        cols:        
          - 'cost'
          - 'actions'
          - 'impressions'
          - 'offsite_conversion_value_fb_pixel_purchase'
          - 'reach'
          - 'unique_action_link_click'
        
    - get_relative_date:
        cols:
          ID_col: 'ad_id'
          Date_col: 'date'
    
    - get_accum_cols:
        cols: 
          ID_col: 'ad_id'
          other_cols:
            - cost
            - impressions
            - offsite_conversion_value_fb_pixel_purchase
            - reach
            - unique_action_link_click
        
     
    
    - get_dif_from_previous_days:
        cols: 
        - cost
        - impressions
        - offsite_conversion_value_fb_pixel_purchase
        - reach
        - unique_action_link_click
        - accum_cost
        - accum_impressions
        - accum_offsite_conversion_value_fb_pixel_purchase
        - accum_reach
        - accum_unique_action_link_click
        days_back: 5 
    # get the roas 
    - roas:
        cols:
          Cost_col: 'cost'
          Rev_col: 'offsite_conversion_value_fb_pixel_purchase'
          name_new_col: 'Roas'

    # get the accum_roas 
    - roas:
        cols:
          Cost_col: 'accum_cost'
          Rev_col: 'accum_offsite_conversion_value_fb_pixel_purchase'
          name_new_col: 'accum_Roas'

    - create_target_max_ratio_roas:
        cols:
          Cost_col: 'cost'
          ID_col: 'ad_id'
          min_cost_threshold: 10
          target_col: 'accum_cost'
          new_target_name: 'target'
    
  data_split:
    split_col: 'ad_id'
    target_col: 'target'
    train_ratio: 0.6
    val_ratio: 0.2
    test_ratio: 0.2
