apiVersion: batch/v1
kind: CronJob
metadata:
  name: roas-prediction-cron
  namespace: default
spec:
  schedule: '0 1 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: roas-prediction-container
              image: 450122606188.dkr.ecr.us-east-1.amazonaws.com/roas-prediction:latest
              imagePullPolicy: Always
              env:
                - name: MONGO_URL
                  value: mongodb+srv://eran:MzI4f8okS2763d8Q@tmscluster.jtyul.mongodb.net/test
          restartPolicy: Never
          concurrencyPolicy: Forbid
          
